name: BreathFlow
options:
  bundleIdPrefix: com.aluis
  deploymentTarget:
    iOS: "16.2"

targets:
  BreathFlow:
    type: application
    platform: iOS
    sources:
      - BreathFlow
      - Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aluis.breathflow
        CODE_SIGN_ENTITLEMENTS: BreathFlow/BreathFlow.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_NSSupportsLiveActivities: YES
        INFOPLIST_KEY_UIBackgroundModes: audio
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_CFBundleDisplayName: BreathFlow
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ITSAppUsesNonExemptEncryption: NO
        INFOPLIST_KEY_NSHealthShareUsageDescription: "BreathFlow saves your breathing sessions as Mindful Minutes in Apple Health to help track your wellness."
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "BreathFlow saves your breathing sessions as Mindful Minutes in Apple Health."
        INFOPLIST_KEY_NSUserNotificationsUsageDescription: "BreathFlow sends daily reminders to help you maintain your breathing practice streak."
