import Foundation

struct AffirmationQuotes {
    static let quotes: [String] = [
        "Breathe in peace, breathe out stress.",
        "You are exactly where you need to be.",
        "Every breath is a fresh start.",
        "Calm is your superpower.",
        "You chose yourself today. That matters.",
        "Stillness is strength.",
        "This moment is enough.",
        "You are worthy of peace.",
        "Let go of what you cannot control.",
        "Your breath is your anchor.",
        "Progress, not perfection.",
        "You are stronger than you know.",
        "Peace begins with a single breath.",
        "Be gentle with yourself.",
        "You showed up for yourself today.",
        "Inhale courage, exhale fear.",
        "Your presence is a gift.",
        "Trust the process.",
        "You are doing better than you think.",
        "Rest is productive.",
        "Your calm ripples outward.",
        "One breath at a time.",
        "You matter.",
        "Embrace the pause.",
        "Clarity comes from stillness.",
        "You are resilient.",
        "This too shall pass.",
        "Your peace is worth protecting.",
        "Slow down. You're doing fine.",
        "Breathe deeply. Live fully.",
        "You are more than your thoughts.",
        "Serenity is always within reach.",
        "Your mind deserves this rest.",
        "Small steps lead to big changes.",
        "You are capable of great things.",
        "Let your breath guide you home.",
        "Tension released. Balance restored.",
        "You deserve moments of calm.",
        "Inner peace is always available.",
        "Your well-being comes first.",
        "Be proud of this moment.",
        "Breathe. Believe. Become.",
        "You are healing with every breath.",
        "Patience is self-love in action.",
        "Your energy is renewed.",
        "Find joy in the simple things.",
        "You are grounded and centered.",
        "Let peace flow through you.",
        "This is your time to recharge.",
        "You are whole and complete.",
        "Embrace your journey.",
        "Your breath connects you to now.",
        "Release what no longer serves you.",
        "You are at peace with yourself.",
        "Every exhale is a letting go.",
        "You create your own calm.",
        "Mindfulness is a gift you give yourself.",
        "Your spirit is unbreakable.",
        "Breathing is believing.",
        "You are present. You are powerful.",
        "Silence nurtures the soul.",
        "Your heart knows the way.",
        "Be here now.",
        "You are a work in progress, and that's okay.",
        "Peace is not found, it's created.",
        "Your breath is your medicine.",
        "You are deserving of this moment.",
        "Let stillness speak.",
        "You are connected to all that is good.",
        "Gratitude transforms everything.",
        "Your mind is clear. Your heart is open.",
        "Embrace the beauty of slowing down.",
        "You are safe in this moment.",
        "Breathe through it.",
        "Your calm mind attracts positive energy.",
        "You are in control of your peace.",
        "Let go and let be.",
        "You are exactly enough.",
        "This breath is a blessing.",
        "Your stillness has power.",
        "You carry peace within you.",
        "Honor your need for rest.",
        "You are becoming who you're meant to be.",
        "Every moment is a new beginning.",
        "Your awareness is your strength.",
        "Tranquility is your birthright.",
        "You are aligned with your purpose.",
        "Breathe in love. Breathe out gratitude.",
        "You have everything you need within.",
        "This practice is an act of self-love.",
        "Your breath tells your body it's safe.",
        "You are anchored in the present.",
        "Let each breath cleanse your mind.",
        "You are worthy of this peace.",
        "Stillness reveals answers.",
        "Your journey is uniquely yours.",
        "Breathe. You've got this.",
        "You are surrounded by possibility.",
        "Your calm is contagious.",
        "You honored yourself today. Well done."
    ]

    static func random() -> String {
        quotes.randomElement() ?? quotes[0]
    }
}
